apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: rrcl36b5z-python
  janus-idp.io/tekton: rrcl36b5z-python
  backstage.io/kubernetes-id: rrcl36b5z-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: rrcl36b5z-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
