apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: rrcl36b5z-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rrcl36b5z-python 
  name: rrcl36b5z-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: rrcl36b5z-python 
